# Copyright (c) 2026 Ramin Allazov (JavaAZE). All Rights Reserved.
# OpenTelemetry Collector — dev stack for Story 6.2 (optional compose profile).
# Receives OTLP from dirijor-core / openclaw-wrapper and forwards traces to Tempo.

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
